version: "3.7"

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis_container
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORDS=yes

  server:
    container_name: backend_container
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    command: npm run dev
    depends_on:
      - redis
